apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-ztp-spoke-sno
spec:
  description: Tekton Pipeline to deploy Kubeframe Spoke SNO cluster
  params:
    - name: git-url
      type: string
      default: "https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable.git"
    - name: git-revision
      type: string
      default: "main"
    - name: ztp-container-image
      type: string
      default: "quay.io/jparrill/ztp-pipeline:latest"
    - name: kubeconfig
      type: string
    - name: spokes-config
      type: string
  workspaces:
    - name: ztp
  tasks:

  # Git Pull
  - name: fetch-from-git
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
    workspaces:
      - name: ztp
        workspace: ztp

  # Preflight
  - name: pre-flight
    taskRef:
      name: common-pre-flight
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
    runAfter:
      - fetch-from-git
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy Spokes
  - name: deploy-spokes
    taskRef:
      name: spoke-deploy-spoke-sno
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
    runAfter:
      - pre-flight
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy MetalLB
  - name: deploy-metallb
    taskRef:
      name: spoke-deploy-metallb-sno
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
    runAfter:
      - deploy-spokes
    workspaces:
      - name: ztp
        workspace: ztp


  # Detach Spoke Cluster
  - name: detach-cluster
    taskRef:
      name: spoke-detach-cluster
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
    runAfter:
      - deploy-metallb
    workspaces:
      - name: ztp
        workspace: ztp
